### ISSUE TITLE
Integration of a WIFI SmartControl Hub - easier?

### ISSUE THREAD

**Issue by crazy-jackrabbit** [rubenbe/comfospottwin40#1]
Hello Ruben,

it might be easier to use Getair's WIFI SmartControl Hub and integrate an IoT device through it. (I'm following your work excitedly and eager to see a solution. I would love to use your work later to integrate my ComfoSpot into KNX).

Greetings,
Sven

Manufacturer (Getair)(LED-, Touch- and Wifi-Control)
https://www.getair.eu/en/control-unit/app-and-voice-control/

Customer from Getair:
Kermi: (LED-, Touch- and Wifi-Control)
https://www.kermi.de/raumklima/produkte/wohnraumlueftung/dezentrales-system/
ZewoTherm (LED-, Touch- and Wifi-Control)
https://www.zewotherm.com/de/produkte/wohnraumlueftung/dezentrale-wohnraumlueftung/lueftungsgeraete-smart-steuern.html
Zehnder: (LED- and Touch-Control)
https://www.zehnder-systems.de/produkte-und-systeme/komfortable-wohnraumlueftung/comfospot-twin40

**Comment by rubenbe** [comment]
Hi Sven!

Sorry for the delayed answer. It hadn't the time to continue on the project and missed your issue.

Thanks for the links. I'll stick to my solution for now and try to integrate over mqtt with home assistant.
As such everything works offline and is properly integrated.

It seems that Zehnder does not distribute the wifi control, but I guess it would be compatible.

I'll update my list of compatible with the Kermi manufacturer. And mention that the GetAir is the OEM. Thanks for the info!

I do now have some progress on controlling the fans, but it's not ready to be pushed yet.
