### ISSUE TITLE
Viessmann Vitovent 050-D 

### ISSUE THREAD

**Issue by Phi2k** [rubenbe/comfospottwin40#4]
Just in case this helps somebody. I’m pretty sure that this system is also compatible. 
I am not able to test.

**Comment by rubenbe** [comment]
Thanks for the pointer!
It seems that the 50-D is using another PWM based system.
But based on what I find, the 100-D is certainly a copy.

[Viessmann-Vitovent-100-D](https://www.amazon.de/-/en/Viessmann-Touch-Control-Panel-Vitovent/dp/B073ZJTY3P)

**Comment by rubenbe** [comment]
Thanks!
https://github.com/rubenbe/comfospottwin40/commit/fe5bf36c41aae4b2cf954ab72b48826916febd37
